# Generated by Django 5.2.8 on 2025-11-07 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
                ('website', models.URLField(blank=True)),
                ('partnership_type', models.CharField(choices=[('funding', 'Funding Partner'), ('program', 'Program Partner'), ('technical', 'Technical Support')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(help_text='Short description for cards')),
                ('full_description', models.TextField(help_text='Full project details')),
                ('category', models.CharField(choices=[('water', 'Water'), ('education', 'Education'), ('health', 'Health'), ('women', "Women's Empowerment"), ('agriculture', 'Agriculture'), ('youth', 'Youth')], max_length=20)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('paused', 'Paused')], default='planning', max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('target_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('metrics', models.JSONField(blank=True, default=dict, help_text='Project metrics as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('excerpt', models.TextField(help_text='Short excerpt for cards')),
                ('content', models.TextField(help_text='Full article content')),
                ('category', models.CharField(choices=[('success_story', 'Success Story'), ('event', 'Event'), ('update', 'Update'), ('press', 'Press')], max_length=20)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
