# Generated by Django 5.2.8 on 2025-11-07 22:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('total_donations', models.DecimalField(decimal_places=2, max_digits=12)),
                ('program_expenses_percentage', models.DecimalField(decimal_places=2, help_text='Percentage spent on programs', max_digits=5)),
                ('fundraising_expenses_percentage', models.DecimalField(decimal_places=2, help_text='Percentage spent on fundraising', max_digits=5)),
                ('admin_expenses_percentage', models.DecimalField(decimal_places=2, help_text='Percentage spent on administration', max_digits=5)),
                ('report_file', models.FileField(help_text='PDF report file', upload_to='reports/')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('year',)},
            },
        ),
        migrations.CreateModel(
            name='TransparencyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('donation_total', 'Total Donations'), ('projects_funded', 'Projects Funded'), ('people_helped', 'People Helped'), ('volunteers_active', 'Active Volunteers'), ('wells_built', 'Wells Built'), ('students_sponsored', 'Students Sponsored'), ('families_supported', 'Families Supported')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly'), ('all_time', 'All Time')], max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'metric_type'],
                'unique_together': {('metric_type', 'period', 'date')},
            },
        ),
    ]
